# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ffb0d2f8637b49a09fd73fe6ec21af92f465e1071c43f1687fd5aea44d84a33a33fdac7f4d0731d72534c9369631a39c1feaf71b8273ceac60d9e8ecf2126773

test:
  secret_key_base: 5a82478026b11e22e16cf93af9142baa575505a129c5210f5d3076674f5320f2aff7f781b0d90591b260fb65479e04099351b355c0da954dc8fc9c82af06cadb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
